### ISSUE TITLE
syntax error at or near "lvIni"

### ISSUE THREAD

**Issue by racherb** [codacy/codacy-sqlint#12]
When I apply Codacity to my PL/SQL code I get the following error:

**syntax error at or near "lvIni"**

Code segment:

```
   FUNCTION fbGetPvd(fpdAnalysisDay IN DATE) RETURN BOOLEAN IS
      lvcPrg CONSTANT VARCHAR2(61) := gvcPkg || 'fbGetPvd';
      ldResume DATE;
      lvIni    VARCHAR2(50);
      lvFin    VARCHAR2(50);
      lvSQL    VARCHAR2(2000);
      ...
```
**Question:** Is this a error? Can Codacity analyze Oracle PL/SQL code?

**Comment by franciscodua** [comment]
Hi @racherb 

Currently, we have three different tools to analyse SQL files.
[TSQLlint](https://github.com/tsqllint/tsqllint/) - that analyses T-SQL files
[SQLint](https://github.com/purcell/sqlint) - that supports ANSI and PostgreSQL syntaxes
[PMD](https://pmd.github.io/) - that supports PL/SQL.

Make sure you only have PMD enabled in your project (disabled the other two if necessary).

Let us know if this suits your use case.

**Comment by racherb** [comment]
It worked very well! Thank you!
